In [7]:
import pandas as pd

In [8]:
kospi = pd.read_csv("../test_feature/KOSPI.csv")
kospi

              날짜        종가        시가        고가        저가      거래량    변동 %
0   2023- 11- 03  2,366.42  2,365.59  2,370.28  2,351.83  527.22K   0.99%
1   2023- 11- 02  2,343.12  2,336.48  2,351.91  2,333.41  377.46K   1.81%
2   2023- 11- 01  2,301.56  2,292.89  2,312.15  2,288.64  358.16M   1.03%
3   2023- 10- 31  2,277.99  2,318.39  2,322.45  2,273.97  394.98M  -1.41%
4   2023- 10- 30  2,310.55  2,292.34  2,317.75  2,292.34  444.84M   0.34%
5   2023- 10- 27  2,302.81  2,311.59  2,321.84  2,293.05  514.88M   0.16%
6   2023- 10- 26  2,299.08  2,325.82  2,330.55  2,299.08  531.07M  -2.71%
7   2023- 10- 25  2,363.17  2,389.23  2,389.90  2,362.69  440.81M  -0.85%
8   2023- 10- 24  2,383.51  2,371.55  2,384.14  2,326.67  444.16M   1.12%
9   2023- 10- 23  2,357.02  2,370.07  2,375.79  2,354.70  395.93M  -0.76%
10  2023- 10- 20  2,375.00  2,391.54  2,394.67  2,364.01  521.21M  -1.69%
11  2023- 10- 19  2,415.80  2,431.92  2,433.45  2,412.55  756.95M  -1.90%
12  2023- 10- 18  2,462.60  2,452.05  2,465.33  2,450.78  911.55M   0.10%
13  2023- 10- 17  2,460.17  2,454.14  2,466.87  2,449.42  509.38M   0.98%
14  2023- 10- 16  2,436.24  2,442.43  2,453.77  2,422.52  788.36M  -0.81%
15  2023- 10- 13  2,456.15  2,460.85  2,466.62  2,452.83  582.88M  -0.95%
16  2023- 10- 12  2,479.82  2,465.19  2,479.82  2,464.84  515.45M   1.21%
17  2023- 10- 11  2,450.08  2,436.52  2,463.56  2,436.52  446.95M   1.98%
18  2023- 10- 10  2,402.58  2,436.58  2,448.24  2,402.44  416.00M  -0.26%
19  2023- 10- 06  2,408.73  2,408.81  2,421.18  2,403.92  289.39M   0.21%
20  2023- 10- 05  2,403.60  2,423.35  2,426.61  2,402.50  451.72M  -0.09%
21  2023- 10- 04  2,405.69  2,435.78  2,435.78  2,402.84  424.86M  -2.41%

In [9]:
kospi = kospi[::-1]
kospi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 21 to 0
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      22 non-null     object
 1   종가      22 non-null     object
 2   시가      22 non-null     object
 3   고가      22 non-null     object
 4   저가      22 non-null     object
 5   거래량     22 non-null     object
 6   변동 %    22 non-null     object
dtypes: object(7)
memory usage: 1.3+ KB

In [10]:
kospi = kospi.reset_index(drop=True)

In [11]:
kospi

              날짜        종가        시가        고가        저가      거래량    변동 %
0   2023- 10- 04  2,405.69  2,435.78  2,435.78  2,402.84  424.86M  -2.41%
1   2023- 10- 05  2,403.60  2,423.35  2,426.61  2,402.50  451.72M  -0.09%
2   2023- 10- 06  2,408.73  2,408.81  2,421.18  2,403.92  289.39M   0.21%
3   2023- 10- 10  2,402.58  2,436.58  2,448.24  2,402.44  416.00M  -0.26%
4   2023- 10- 11  2,450.08  2,436.52  2,463.56  2,436.52  446.95M   1.98%
5   2023- 10- 12  2,479.82  2,465.19  2,479.82  2,464.84  515.45M   1.21%
6   2023- 10- 13  2,456.15  2,460.85  2,466.62  2,452.83  582.88M  -0.95%
7   2023- 10- 16  2,436.24  2,442.43  2,453.77  2,422.52  788.36M  -0.81%
8   2023- 10- 17  2,460.17  2,454.14  2,466.87  2,449.42  509.38M   0.98%
9   2023- 10- 18  2,462.60  2,452.05  2,465.33  2,450.78  911.55M   0.10%
10  2023- 10- 19  2,415.80  2,431.92  2,433.45  2,412.55  756.95M  -1.90%
11  2023- 10- 20  2,375.00  2,391.54  2,394.67  2,364.01  521.21M  -1.69%
12  2023- 10- 23  2,357.02  2,370.07  2,375.79  2,354.70  395.93M  -0.76%
13  2023- 10- 24  2,383.51  2,371.55  2,384.14  2,326.67  444.16M   1.12%
14  2023- 10- 25  2,363.17  2,389.23  2,389.90  2,362.69  440.81M  -0.85%
15  2023- 10- 26  2,299.08  2,325.82  2,330.55  2,299.08  531.07M  -2.71%
16  2023- 10- 27  2,302.81  2,311.59  2,321.84  2,293.05  514.88M   0.16%
17  2023- 10- 30  2,310.55  2,292.34  2,317.75  2,292.34  444.84M   0.34%
18  2023- 10- 31  2,277.99  2,318.39  2,322.45  2,273.97  394.98M  -1.41%
19  2023- 11- 01  2,301.56  2,292.89  2,312.15  2,288.64  358.16M   1.03%
20  2023- 11- 02  2,343.12  2,336.48  2,351.91  2,333.41  377.46K   1.81%
21  2023- 11- 03  2,366.42  2,365.59  2,370.28  2,351.83  527.22K   0.99%

In [12]:
kospi = kospi[['날짜', '종가', '시가', '변동 %']]

In [13]:
kospi['변동 %'] = kospi['변동 %'].astype(str)
kospi["변동 %"] = kospi["변동 %"].str.rstrip('%')
kospi["변동 %"] = kospi["변동 %"].astype(float)

kospi["시가"] = kospi["시가"].str.replace(',', '')
kospi["시가"] = kospi["시가"].astype(float)

kospi["종가"] = kospi["종가"].str.replace(',', '')
kospi["종가"] = kospi["종가"].astype(float)

/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/2512034181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi['변동 %'] = kospi['변동 %'].astype(str)
/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/2512034181.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi["변동 %"] = kospi["변동 %"].str.rstrip('%')
/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/2512034181.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi["변동 %"] = kospi["변동 %"].astype(float)
/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/2512034181.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi["시가"] = kospi["시가"].str.replace(',', '')
/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/2512034181.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi["시가"] = kospi["시가"].astype(float)
/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/2512034181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi["종가"] = kospi["종가"].str.replace(',', '')
/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/2512034181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi["종가"] = kospi["종가"].astype(float)

In [14]:
kospi['변동 %'] = kospi['변동 %'].shift(1)
kospi

/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/1931990411.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi['변동 %'] = kospi['변동 %'].shift(1)

              날짜       종가       시가  변동 %
0   2023- 10- 04  2405.69  2435.78   NaN
1   2023- 10- 05  2403.60  2423.35 -2.41
2   2023- 10- 06  2408.73  2408.81 -0.09
3   2023- 10- 10  2402.58  2436.58  0.21
4   2023- 10- 11  2450.08  2436.52 -0.26
5   2023- 10- 12  2479.82  2465.19  1.98
6   2023- 10- 13  2456.15  2460.85  1.21
7   2023- 10- 16  2436.24  2442.43 -0.95
8   2023- 10- 17  2460.17  2454.14 -0.81
9   2023- 10- 18  2462.60  2452.05  0.98
10  2023- 10- 19  2415.80  2431.92  0.10
11  2023- 10- 20  2375.00  2391.54 -1.90
12  2023- 10- 23  2357.02  2370.07 -1.69
13  2023- 10- 24  2383.51  2371.55 -0.76
14  2023- 10- 25  2363.17  2389.23  1.12
15  2023- 10- 26  2299.08  2325.82 -0.85
16  2023- 10- 27  2302.81  2311.59 -2.71
17  2023- 10- 30  2310.55  2292.34  0.16
18  2023- 10- 31  2277.99  2318.39  0.34
19  2023- 11- 01  2301.56  2292.89 -1.41
20  2023- 11- 02  2343.12  2336.48  1.03
21  2023- 11- 03  2366.42  2365.59  1.81

In [15]:
kospi = kospi.dropna()

In [16]:
kospi['종가'] = kospi['종가'].shift(1)

/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/3770697944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi['종가'] = kospi['종가'].shift(1)

In [17]:
kospi['야간변화율'] = round(((kospi['시가'] - kospi['종가']) / kospi['종가']) * 100, 3)

/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_46423/371561438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kospi['야간변화율'] = round(((kospi['시가'] - kospi['종가']) / kospi['종가']) * 100, 3)

In [18]:
kospi = kospi.dropna()
kospi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 2 to 21
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      20 non-null     object
 1   종가      20 non-null     float64
 2   시가      20 non-null     float64
 3   변동 %    20 non-null     float64
 4   야간변화율   20 non-null     float64
dtypes: float64(4), object(1)
memory usage: 960.0+ bytes

In [19]:
kospi['날짜'] = pd.to_datetime(kospi['날짜'])

In [22]:
kospi = kospi[1:]

In [23]:
kospi = kospi.reset_index(drop=True)

In [24]:
kospi

           날짜       종가       시가  변동 %  야간변화율
0  2023-10-10  2408.73  2436.58  0.21  1.156
1  2023-10-11  2402.58  2436.52 -0.26  1.413
2  2023-10-12  2450.08  2465.19  1.98  0.617
3  2023-10-13  2479.82  2460.85  1.21 -0.765
4  2023-10-16  2456.15  2442.43 -0.95 -0.559
5  2023-10-17  2436.24  2454.14 -0.81  0.735
6  2023-10-18  2460.17  2452.05  0.98 -0.330
7  2023-10-19  2462.60  2431.92  0.10 -1.246
8  2023-10-20  2415.80  2391.54 -1.90 -1.004
9  2023-10-23  2375.00  2370.07 -1.69 -0.208
10 2023-10-24  2357.02  2371.55 -0.76  0.616
11 2023-10-25  2383.51  2389.23  1.12  0.240
12 2023-10-26  2363.17  2325.82 -0.85 -1.581
13 2023-10-27  2299.08  2311.59 -2.71  0.544
14 2023-10-30  2302.81  2292.34  0.16 -0.455
15 2023-10-31  2310.55  2318.39  0.34  0.339
16 2023-11-01  2277.99  2292.89 -1.41  0.654
17 2023-11-02  2301.56  2336.48  1.03  1.517
18 2023-11-03  2343.12  2365.59  1.81  0.959

In [25]:
kospi.reset_index(drop=True)[['날짜', '변동 %', '야간변화율']].to_csv('../test_feature/clean_feature/kospi.csv')