In [14]:
import pandas as pd

In [15]:
nas = pd.read_csv("../test_feature/NASDAQ.csv")
nas

              날짜         종가         시가         고가         저가      거래량    변동 %
0   2023- 11- 02  13,294.19  13,230.49  13,302.18  13,177.64    1.03B   1.78%
1   2023- 11- 01  13,061.47  12,887.06  13,072.42  12,875.20  937.65M   1.64%
2   2023- 10- 31  12,851.24  12,786.62  12,859.40  12,697.04  914.04M   0.48%
3   2023- 10- 30  12,789.48  12,750.46  12,842.96  12,691.56  801.65M   1.16%
4   2023- 10- 27  12,643.01  12,718.69  12,772.43  12,600.57  856.38M   0.38%
5   2023- 10- 26  12,595.61  12,768.97  12,818.14  12,543.86  941.24M  -1.76%
6   2023- 10- 25  12,821.22  13,039.86  13,042.52  12,804.30  950.80M  -2.43%
7   2023- 10- 24  13,139.88  13,084.99  13,170.39  13,022.85  878.12M   0.93%
8   2023- 10- 23  13,018.33  12,930.85  13,143.22  12,848.83  859.07M   0.27%
9   2023- 10- 20  12,983.81  13,157.77  13,177.35  12,977.43    1.03B  -1.53%
10  2023- 10- 19  13,186.17  13,354.80  13,404.73  13,157.33  920.00M  -0.96%
11  2023- 10- 18  13,314.30  13,439.68  13,499.74  13,275.30  843.06M  -1.62%
12  2023- 10- 17  13,533.75  13,419.87  13,602.25  13,364.74  906.42M  -0.25%
13  2023- 10- 16  13,567.98  13,453.81  13,598.05  13,447.17  832.45M   1.20%
14  2023- 10- 13  13,407.23  13,613.59  13,619.54  13,361.85  843.48M  -1.23%
15  2023- 10- 12  13,574.22  13,672.47  13,714.14  13,491.56  921.27M  -0.63%
16  2023- 10- 11  13,659.68  13,619.21  13,671.11  13,549.29  797.05M   0.71%
17  2023- 10- 10  13,562.84  13,505.81  13,659.63  13,491.81  823.87M   0.58%
18  2023- 10- 09  13,484.24  13,326.22  13,509.30  13,277.48  723.95M   0.39%
19  2023- 10- 06  13,431.34  13,127.68  13,472.27  13,099.03  860.52M   1.60%
20  2023- 10- 05  13,219.83  13,228.12  13,251.18  13,087.57  870.00M  -0.12%
21  2023- 10- 04  13,236.01  13,092.92  13,258.76  13,072.51  854.22M   1.35%
22  2023- 10- 03  13,059.47  13,229.68  13,280.04  13,008.60  889.31M  -1.87%

In [16]:
new_row = {'날짜':['2023- 11- 03']}
new_row = pd.DataFrame(new_row)
new_row.index = [0]
nas = pd.concat([new_row, nas], ignore_index=True)
nas

              날짜         종가         시가         고가         저가      거래량    변동 %
0   2023- 11- 03        NaN        NaN        NaN        NaN      NaN     NaN
1   2023- 11- 02  13,294.19  13,230.49  13,302.18  13,177.64    1.03B   1.78%
2   2023- 11- 01  13,061.47  12,887.06  13,072.42  12,875.20  937.65M   1.64%
3   2023- 10- 31  12,851.24  12,786.62  12,859.40  12,697.04  914.04M   0.48%
4   2023- 10- 30  12,789.48  12,750.46  12,842.96  12,691.56  801.65M   1.16%
5   2023- 10- 27  12,643.01  12,718.69  12,772.43  12,600.57  856.38M   0.38%
6   2023- 10- 26  12,595.61  12,768.97  12,818.14  12,543.86  941.24M  -1.76%
7   2023- 10- 25  12,821.22  13,039.86  13,042.52  12,804.30  950.80M  -2.43%
8   2023- 10- 24  13,139.88  13,084.99  13,170.39  13,022.85  878.12M   0.93%
9   2023- 10- 23  13,018.33  12,930.85  13,143.22  12,848.83  859.07M   0.27%
10  2023- 10- 20  12,983.81  13,157.77  13,177.35  12,977.43    1.03B  -1.53%
11  2023- 10- 19  13,186.17  13,354.80  13,404.73  13,157.33  920.00M  -0.96%
12  2023- 10- 18  13,314.30  13,439.68  13,499.74  13,275.30  843.06M  -1.62%
13  2023- 10- 17  13,533.75  13,419.87  13,602.25  13,364.74  906.42M  -0.25%
14  2023- 10- 16  13,567.98  13,453.81  13,598.05  13,447.17  832.45M   1.20%
15  2023- 10- 13  13,407.23  13,613.59  13,619.54  13,361.85  843.48M  -1.23%
16  2023- 10- 12  13,574.22  13,672.47  13,714.14  13,491.56  921.27M  -0.63%
17  2023- 10- 11  13,659.68  13,619.21  13,671.11  13,549.29  797.05M   0.71%
18  2023- 10- 10  13,562.84  13,505.81  13,659.63  13,491.81  823.87M   0.58%
19  2023- 10- 09  13,484.24  13,326.22  13,509.30  13,277.48  723.95M   0.39%
20  2023- 10- 06  13,431.34  13,127.68  13,472.27  13,099.03  860.52M   1.60%
21  2023- 10- 05  13,219.83  13,228.12  13,251.18  13,087.57  870.00M  -0.12%
22  2023- 10- 04  13,236.01  13,092.92  13,258.76  13,072.51  854.22M   1.35%
23  2023- 10- 03  13,059.47  13,229.68  13,280.04  13,008.60  889.31M  -1.87%

In [17]:
nas = nas.reset_index(drop=True)

In [18]:
nas = nas[::-1]

In [19]:
nas = nas[['날짜', '종가', '시가', '고가', '저가', '변동 %']]

In [20]:
nas['변동 %'] = nas['변동 %'].astype(str)
nas["변동 %"] = nas["변동 %"].str.rstrip('%')
nas["변동 %"] = nas["변동 %"].astype(float)

nas["시가"] = nas["시가"].str.replace(',', '')
nas["시가"] = nas["시가"].astype(float)

nas["종가"] = nas["종가"].str.replace(',', '')
nas["종가"] = nas["종가"].astype(float)

nas["고가"] = nas["고가"].str.replace(',', '')
nas["고가"] = nas["고가"].astype(float)

nas["저가"] = nas["저가"].str.replace(',', '')
nas["저가"] = nas["저가"].astype(float)

In [21]:
nas['변동 %'] = nas['변동 %'].shift(1)
nas

              날짜        종가        시가        고가        저가  변동 %
23  2023- 10- 03  13059.47  13229.68  13280.04  13008.60   NaN
22  2023- 10- 04  13236.01  13092.92  13258.76  13072.51 -1.87
21  2023- 10- 05  13219.83  13228.12  13251.18  13087.57  1.35
20  2023- 10- 06  13431.34  13127.68  13472.27  13099.03 -0.12
19  2023- 10- 09  13484.24  13326.22  13509.30  13277.48  1.60
18  2023- 10- 10  13562.84  13505.81  13659.63  13491.81  0.39
17  2023- 10- 11  13659.68  13619.21  13671.11  13549.29  0.58
16  2023- 10- 12  13574.22  13672.47  13714.14  13491.56  0.71
15  2023- 10- 13  13407.23  13613.59  13619.54  13361.85 -0.63
14  2023- 10- 16  13567.98  13453.81  13598.05  13447.17 -1.23
13  2023- 10- 17  13533.75  13419.87  13602.25  13364.74  1.20
12  2023- 10- 18  13314.30  13439.68  13499.74  13275.30 -0.25
11  2023- 10- 19  13186.17  13354.80  13404.73  13157.33 -1.62
10  2023- 10- 20  12983.81  13157.77  13177.35  12977.43 -0.96
9   2023- 10- 23  13018.33  12930.85  13143.22  12848.83 -1.53
8   2023- 10- 24  13139.88  13084.99  13170.39  13022.85  0.27
7   2023- 10- 25  12821.22  13039.86  13042.52  12804.30  0.93
6   2023- 10- 26  12595.61  12768.97  12818.14  12543.86 -2.43
5   2023- 10- 27  12643.01  12718.69  12772.43  12600.57 -1.76
4   2023- 10- 30  12789.48  12750.46  12842.96  12691.56  0.38
3   2023- 10- 31  12851.24  12786.62  12859.40  12697.04  1.16
2   2023- 11- 01  13061.47  12887.06  13072.42  12875.20  0.48
1   2023- 11- 02  13294.19  13230.49  13302.18  13177.64  1.64
0   2023- 11- 03       NaN       NaN       NaN       NaN  1.78

In [22]:
nas['당일 변동률'] = round((nas['종가'] - nas['시가']) / nas['시가'] * 100, 3)
nas['당일 변화량'] = round(nas['고가'] - nas['저가'], 3)

In [23]:
nas['당일 변동률'] = nas['당일 변동률'].shift(1)
nas['당일 변화량'] = nas['당일 변화량'].shift(1)

In [24]:
nas[5:]

              날짜        종가        시가        고가        저가  변동 %  당일 변동률  당일 변화량
18  2023- 10- 10  13562.84  13505.81  13659.63  13491.81  0.39   1.186  231.82
17  2023- 10- 11  13659.68  13619.21  13671.11  13549.29  0.58   0.422  167.82
16  2023- 10- 12  13574.22  13672.47  13714.14  13491.56  0.71   0.297  121.82
15  2023- 10- 13  13407.23  13613.59  13619.54  13361.85 -0.63  -0.719  222.58
14  2023- 10- 16  13567.98  13453.81  13598.05  13447.17 -1.23  -1.516  257.69
13  2023- 10- 17  13533.75  13419.87  13602.25  13364.74  1.20   0.849  150.88
12  2023- 10- 18  13314.30  13439.68  13499.74  13275.30 -0.25   0.849  237.51
11  2023- 10- 19  13186.17  13354.80  13404.73  13157.33 -1.62  -0.933  224.44
10  2023- 10- 20  12983.81  13157.77  13177.35  12977.43 -0.96  -1.263  247.40
9   2023- 10- 23  13018.33  12930.85  13143.22  12848.83 -1.53  -1.322  199.92
8   2023- 10- 24  13139.88  13084.99  13170.39  13022.85  0.27   0.677  294.39
7   2023- 10- 25  12821.22  13039.86  13042.52  12804.30  0.93   0.419  147.54
6   2023- 10- 26  12595.61  12768.97  12818.14  12543.86 -2.43  -1.677  238.22
5   2023- 10- 27  12643.01  12718.69  12772.43  12600.57 -1.76  -1.358  274.28
4   2023- 10- 30  12789.48  12750.46  12842.96  12691.56  0.38  -0.595  171.86
3   2023- 10- 31  12851.24  12786.62  12859.40  12697.04  1.16   0.306  151.40
2   2023- 11- 01  13061.47  12887.06  13072.42  12875.20  0.48   0.505  162.36
1   2023- 11- 02  13294.19  13230.49  13302.18  13177.64  1.64   1.353  197.22
0   2023- 11- 03       NaN       NaN       NaN       NaN  1.78   0.481  124.54

In [25]:
nas[5:].reset_index(drop=True)[['날짜', '변동 %', '당일 변동률', '당일 변화량']].to_csv('../test_feature/clean_feature/nas.csv')