In [67]:
import pandas as pd

In [68]:
vkospi_half = pd.read_csv('../data/VKOSPI.csv')
vkospi_half

               날짜     종가     시가     고가     저가  거래량     변동 %
0    2023- 10- 31  19.89  19.25  20.12  19.05  NaN   -0.70%
1    2023- 10- 30  20.03  21.04  21.04  19.88  NaN    0.05%
2    2023- 10- 27  20.02  19.98  20.41  19.79  NaN   -5.30%
3    2023- 10- 26  21.14  20.19  21.19  19.87  NaN   13.90%
4    2023- 10- 25  18.56  18.39  18.67  18.29  NaN   -1.38%
..            ...    ...    ...    ...    ...  ...      ...
257  2022- 10- 17  24.40  25.44  25.66  24.31  NaN    1.92%
258  2022- 10- 14  23.94  24.81  24.86  23.94  NaN  -12.05%
259  2022- 10- 13  27.22  25.25  27.47  25.15  NaN   10.25%
260  2022- 10- 12  24.69  25.77  25.77  24.69  NaN   -4.23%
261  2022- 10- 11  25.78  26.53  26.89  25.69  NaN    7.73%

[262 rows x 7 columns]

In [69]:
vkospi = pd.read_csv('../test_feature/VKOSPI.csv')
vkospi[:2]

             날짜     종가     시가     고가     저가  거래량    변동 %
0  2023- 11- 02  17.49  17.73  17.88  17.27  NaN  -6.92%
1  2023- 11- 01  18.79  19.09  19.20  18.74  NaN  -5.53%

In [70]:
vkospi = pd.concat([vkospi[:2], vkospi_half], axis=0)

In [71]:
vkospi

               날짜     종가     시가     고가     저가  거래량     변동 %
0    2023- 11- 02  17.49  17.73  17.88  17.27  NaN   -6.92%
1    2023- 11- 01  18.79  19.09  19.20  18.74  NaN   -5.53%
0    2023- 10- 31  19.89  19.25  20.12  19.05  NaN   -0.70%
1    2023- 10- 30  20.03  21.04  21.04  19.88  NaN    0.05%
2    2023- 10- 27  20.02  19.98  20.41  19.79  NaN   -5.30%
..            ...    ...    ...    ...    ...  ...      ...
257  2022- 10- 17  24.40  25.44  25.66  24.31  NaN    1.92%
258  2022- 10- 14  23.94  24.81  24.86  23.94  NaN  -12.05%
259  2022- 10- 13  27.22  25.25  27.47  25.15  NaN   10.25%
260  2022- 10- 12  24.69  25.77  25.77  24.69  NaN   -4.23%
261  2022- 10- 11  25.78  26.53  26.89  25.69  NaN    7.73%

[264 rows x 7 columns]

In [72]:
new_row = {'날짜':['2023- 11- 03']}
new_row = pd.DataFrame(new_row)
new_row.index = [0]
vkospi = pd.concat([new_row, vkospi], ignore_index=True)
vkospi

               날짜     종가     시가     고가     저가  거래량     변동 %
0    2023- 11- 03    NaN    NaN    NaN    NaN  NaN      NaN
1    2023- 11- 02  17.49  17.73  17.88  17.27  NaN   -6.92%
2    2023- 11- 01  18.79  19.09  19.20  18.74  NaN   -5.53%
3    2023- 10- 31  19.89  19.25  20.12  19.05  NaN   -0.70%
4    2023- 10- 30  20.03  21.04  21.04  19.88  NaN    0.05%
..            ...    ...    ...    ...    ...  ...      ...
260  2022- 10- 17  24.40  25.44  25.66  24.31  NaN    1.92%
261  2022- 10- 14  23.94  24.81  24.86  23.94  NaN  -12.05%
262  2022- 10- 13  27.22  25.25  27.47  25.15  NaN   10.25%
263  2022- 10- 12  24.69  25.77  25.77  24.69  NaN   -4.23%
264  2022- 10- 11  25.78  26.53  26.89  25.69  NaN    7.73%

[265 rows x 7 columns]

In [73]:
vkospi[['종가', '시가']] = vkospi[['종가', '시가']].shift(-1)

In [74]:
vkospi

               날짜     종가     시가     고가     저가  거래량     변동 %
0    2023- 11- 03  17.49  17.73    NaN    NaN  NaN      NaN
1    2023- 11- 02  18.79  19.09  17.88  17.27  NaN   -6.92%
2    2023- 11- 01  19.89  19.25  19.20  18.74  NaN   -5.53%
3    2023- 10- 31  20.03  21.04  20.12  19.05  NaN   -0.70%
4    2023- 10- 30  20.02  19.98  21.04  19.88  NaN    0.05%
..            ...    ...    ...    ...    ...  ...      ...
260  2022- 10- 17  23.94  24.81  25.66  24.31  NaN    1.92%
261  2022- 10- 14  27.22  25.25  24.86  23.94  NaN  -12.05%
262  2022- 10- 13  24.69  25.77  27.47  25.15  NaN   10.25%
263  2022- 10- 12  25.78  26.53  25.77  24.69  NaN   -4.23%
264  2022- 10- 11    NaN    NaN  26.89  25.69  NaN    7.73%

[265 rows x 7 columns]

In [75]:
vkospi = vkospi[::-1]

In [76]:
vkospi

               날짜     종가     시가     고가     저가  거래량     변동 %
264  2022- 10- 11    NaN    NaN  26.89  25.69  NaN    7.73%
263  2022- 10- 12  25.78  26.53  25.77  24.69  NaN   -4.23%
262  2022- 10- 13  24.69  25.77  27.47  25.15  NaN   10.25%
261  2022- 10- 14  27.22  25.25  24.86  23.94  NaN  -12.05%
260  2022- 10- 17  23.94  24.81  25.66  24.31  NaN    1.92%
..            ...    ...    ...    ...    ...  ...      ...
4    2023- 10- 30  20.02  19.98  21.04  19.88  NaN    0.05%
3    2023- 10- 31  20.03  21.04  20.12  19.05  NaN   -0.70%
2    2023- 11- 01  19.89  19.25  19.20  18.74  NaN   -5.53%
1    2023- 11- 02  18.79  19.09  17.88  17.27  NaN   -6.92%
0    2023- 11- 03  17.49  17.73    NaN    NaN  NaN      NaN

[265 rows x 7 columns]

In [77]:
vkospi = vkospi.reset_index(drop=True)

In [78]:
vkospi

               날짜     종가     시가     고가     저가  거래량     변동 %
0    2022- 10- 11    NaN    NaN  26.89  25.69  NaN    7.73%
1    2022- 10- 12  25.78  26.53  25.77  24.69  NaN   -4.23%
2    2022- 10- 13  24.69  25.77  27.47  25.15  NaN   10.25%
3    2022- 10- 14  27.22  25.25  24.86  23.94  NaN  -12.05%
4    2022- 10- 17  23.94  24.81  25.66  24.31  NaN    1.92%
..            ...    ...    ...    ...    ...  ...      ...
260  2023- 10- 30  20.02  19.98  21.04  19.88  NaN    0.05%
261  2023- 10- 31  20.03  21.04  20.12  19.05  NaN   -0.70%
262  2023- 11- 01  19.89  19.25  19.20  18.74  NaN   -5.53%
263  2023- 11- 02  18.79  19.09  17.88  17.27  NaN   -6.92%
264  2023- 11- 03  17.49  17.73    NaN    NaN  NaN      NaN

[265 rows x 7 columns]

In [79]:
vkospi['VKOSPI 당일 변동율'] = round((vkospi['종가'] - vkospi['시가']) / vkospi['시가'] * 100, 3)

In [80]:
vkospi

               날짜     종가     시가     고가     저가  거래량     변동 %  VKOSPI 당일 변동율
0    2022- 10- 11    NaN    NaN  26.89  25.69  NaN    7.73%            NaN
1    2022- 10- 12  25.78  26.53  25.77  24.69  NaN   -4.23%         -2.827
2    2022- 10- 13  24.69  25.77  27.47  25.15  NaN   10.25%         -4.191
3    2022- 10- 14  27.22  25.25  24.86  23.94  NaN  -12.05%          7.802
4    2022- 10- 17  23.94  24.81  25.66  24.31  NaN    1.92%         -3.507
..            ...    ...    ...    ...    ...  ...      ...            ...
260  2023- 10- 30  20.02  19.98  21.04  19.88  NaN    0.05%          0.200
261  2023- 10- 31  20.03  21.04  20.12  19.05  NaN   -0.70%         -4.800
262  2023- 11- 01  19.89  19.25  19.20  18.74  NaN   -5.53%          3.325
263  2023- 11- 02  18.79  19.09  17.88  17.27  NaN   -6.92%         -1.572
264  2023- 11- 03  17.49  17.73    NaN    NaN  NaN      NaN         -1.354

[265 rows x 8 columns]

In [84]:
vkospi[206:]

            날짜     종가     시가     고가     저가  거래량    변동 %  VKOSPI 당일 변동율
206 2023-08-07  15.55  15.84  15.98  15.34  NaN   1.03%         -1.831
207 2023-08-08  15.71  15.97  16.04  14.86  NaN  -1.97%         -1.628
208 2023-08-09  15.40  15.12  15.32  14.00  NaN  -8.12%          1.852
209 2023-08-10  14.15  15.32  14.52  13.86  NaN  -1.06%         -7.637
210 2023-08-11  14.00  14.50  13.80  13.43  NaN  -4.00%         -3.448
211 2023-08-14  13.44  13.68  14.53  13.84  NaN   5.21%         -1.754
212 2023-08-16  14.14  14.01  15.39  14.83  NaN   7.14%          0.928
213 2023-08-17  15.15  14.89  16.74  15.50  NaN   2.77%          1.746
214 2023-08-18  15.57  15.86  17.09  15.75  NaN   2.95%         -1.828
215 2023-08-21  16.03  16.92  16.29  15.63  NaN   0.00%         -5.260
216 2023-08-22  16.03  16.28  15.51  15.02  NaN  -4.37%         -1.536
217 2023-08-23  15.33  15.51  15.72  14.96  NaN  -2.35%         -1.161
218 2023-08-24  14.97  15.72  14.33  13.80  NaN  -6.88%         -4.771
219 2023-08-25  13.94  14.31  15.23  14.69  NaN   6.60%         -2.586
220 2023-08-28  14.86  15.20  14.57  14.15  NaN  -4.58%         -2.237
221 2023-08-29  14.18  14.53  14.04  13.44  NaN  -4.87%         -2.409
222 2023-08-30  13.49  13.89  13.19  12.86  NaN  -3.26%         -2.880
223 2023-08-31  13.05  13.14  12.91  12.70  NaN  -2.07%         -0.685
224 2023-09-01  12.78  12.88  12.77  12.42  NaN  -1.96%         -0.776
225 2023-09-04  12.53  12.74  12.88  12.42  NaN  -0.32%         -1.648
226 2023-09-05  12.49  12.82  12.53  12.31  NaN  -0.56%         -2.574
227 2023-09-06  12.42  12.51  12.56  12.27  NaN   0.32%         -0.719
228 2023-09-07  12.46  12.39  12.72  12.39  NaN   1.85%          0.565
229 2023-09-08  12.69  12.55  12.79  12.40  NaN  -2.29%          1.116
230 2023-09-11  12.40  12.51  12.73  12.37  NaN   0.16%         -0.879
231 2023-09-12  12.42  12.55  12.55  12.21  NaN  -0.16%         -1.036
232 2023-09-13  12.40  12.24  12.66  12.27  NaN   1.94%          1.307
233 2023-09-14  12.64  12.54  12.43  11.96  NaN  -4.91%          0.797
234 2023-09-15  12.02  12.42  12.11  11.72  NaN  -2.41%         -3.221
235 2023-09-18  11.73  11.92  12.90  12.69  NaN   9.55%         -1.594
236 2023-09-19  12.85  12.76  13.11  12.83  NaN   0.78%          0.705
237 2023-09-20  12.95  12.85  13.18  13.00  NaN   0.62%          0.778
238 2023-09-21  13.03  13.11  14.00  13.23  NaN   7.14%         -0.610
239 2023-09-22  13.96  13.33  15.51  14.12  NaN   1.58%          4.726
240 2023-09-25  14.18  15.25  14.72  14.04  NaN  -0.56%         -7.016
241 2023-09-26  14.10  14.72  14.88  14.11  NaN   4.54%         -4.212
242 2023-09-27  14.74  14.12  15.43  14.94  NaN   2.31%          4.391
243 2023-10-04  15.08  15.43  18.13  17.16  NaN  19.96%         -2.268
244 2023-10-05  18.09  17.16  17.62  16.96  NaN  -4.15%          5.420
245 2023-10-06  17.34  17.10  17.39  16.83  NaN   0.29%          1.404
246 2023-10-10  17.39  17.11  17.58  16.61  NaN   0.98%          1.636
247 2023-10-11  17.56  16.77  16.82  16.33  NaN  -4.67%          4.711
248 2023-10-12  16.74  16.78  16.32  15.70  NaN  -6.21%         -0.238
249 2023-10-13  15.70  16.21  16.35  15.93  NaN   1.59%         -3.146
250 2023-10-16  15.95  16.28  17.63  16.76  NaN   7.02%         -2.027
251 2023-10-17  17.07  16.92  16.49  15.98  NaN  -5.21%          0.887
252 2023-10-18  16.18  16.23  16.43  15.90  NaN  -1.11%         -0.308
253 2023-10-19  16.00  16.36  18.23  17.18  NaN  13.94%         -2.200
254 2023-10-20  18.23  17.34  20.36  18.95  NaN   7.13%          5.133
255 2023-10-23  19.53  19.02  19.93  19.41  NaN   0.61%          2.681
256 2023-10-24  19.65  19.92  20.14  18.74  NaN  -4.22%         -1.355
257 2023-10-25  18.82  19.07  18.67  18.29  NaN  -1.38%         -1.311
258 2023-10-26  18.56  18.39  21.19  19.87  NaN  13.90%          0.924
259 2023-10-27  21.14  20.19  20.41  19.79  NaN  -5.30%          4.705
260 2023-10-30  20.02  19.98  21.04  19.88  NaN   0.05%          0.200
261 2023-10-31  20.03  21.04  20.12  19.05  NaN  -0.70%         -4.800
262 2023-11-01  19.89  19.25  19.20  18.74  NaN  -5.53%          3.325
263 2023-11-02  18.79  19.09  17.88  17.27  NaN  -6.92%         -1.572
264 2023-11-03  17.49  17.73    NaN    NaN  NaN     NaN         -1.354

In [82]:
vkospi['날짜'] = pd.to_datetime(vkospi['날짜'])

In [85]:
vkospi[125:][['날짜', 'VKOSPI 당일 변동율']].reset_index(drop=True).to_csv("./vkospi_half.csv")

In [86]:
vkospi[206:][['날짜', 'VKOSPI 당일 변동율']].reset_index(drop=True).to_csv("./vkospi_2month.csv")