In [1]:
import pandas as pd

In [4]:
label = pd.read_csv('.././dataset/clean_feature/VKOSPI_Label.csv', index_col=0)
label

            날짜  VKOSPI_Label
0   2023-07-31             0
1   2023-08-01             0
2   2023-08-02             1
3   2023-08-03             1
4   2023-08-04             0
5   2023-08-07             0
6   2023-08-08             1
7   2023-08-09             0
8   2023-08-10             0
9   2023-08-11             0
10  2023-08-14             1
11  2023-08-16             1
12  2023-08-17             0
13  2023-08-18             0
14  2023-08-21             0
15  2023-08-22             0
16  2023-08-23             0
17  2023-08-24             0
18  2023-08-25             0
19  2023-08-28             0
20  2023-08-29             0
21  2023-08-30             0
22  2023-08-31             0
23  2023-09-01             0
24  2023-09-04             0
25  2023-09-05             0
26  2023-09-06             1
27  2023-09-07             1
28  2023-09-08             0
29  2023-09-11             0
30  2023-09-12             1
31  2023-09-13             1
32  2023-09-14             0
33  2023-09-15             0
34  2023-09-18             1
35  2023-09-19             1
36  2023-09-20             0
37  2023-09-21             1
38  2023-09-22             0
39  2023-09-25             0
40  2023-09-26             1
41  2023-09-27             0
42  2023-10-04             1
43  2023-10-05             1
44  2023-10-06             1
45  2023-10-10             1
46  2023-10-11             0
47  2023-10-12             0
48  2023-10-13             0
49  2023-10-16             1
50  2023-10-17             0
51  2023-10-18             0
52  2023-10-19             1
53  2023-10-20             1

In [11]:
label['VKOSPI_Label'].value_counts()

VKOSPI_Label
0    34
1    20
Name: count, dtype: int64